config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :students, only: [:index, :show, :new, :create] do
    resources :progresses, only: [:new, :create]
  end
  resources :teachers, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :teacher
  has_many :course_lessons
  has_many :lessons, through: :course_lessons
  has_many :progresses, through: :course_lessons

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/course_lesson.rb
# frozen_string_literal: true

class CourseLesson < ApplicationRecord
  belongs_to :course
  belongs_to :lesson
  has_many :progresses
  has_many :parts, through: :lesson

  delegate :number, to: :lesson, prefix: true

  validates :course, presence: true
  validates :lesson, presence: true
  validates_uniqueness_of :lesson, scope: :course

  scope :available_by_parts, lambda { |parts|
    CourseLesson.includes(:course, :progresses, lesson: :parts)
                .where(parts: { id: parts })
                .order('lessons.number asc')
  }

  def to_s
    "Course: #{course} | Lesson: #{lesson_number} - #{lesson}"
  end
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  has_many :parts
  has_many :course_lessons

  validates :name, presence: true

  def to_s
    name
  end
end

app/models/part.rb
# frozen_string_literal: true

class Part < ApplicationRecord
  belongs_to :lesson
  belongs_to :previous, class_name: 'Part', optional: true
  has_many :progresses

  delegate :number, to: :lesson, prefix: true

  validates :lesson, presence: true
  validates :number, presence: true
  validates :name, presence: true
  validates :previous, uniqueness: true

  scope :by_numbers, lambda { |lesson_number, part_number|
    joins(:lesson).find_by(lessons: { number: lesson_number },
                           number: part_number)
  }
  scope :ordered_parts_with_lesson, lambda {
    Part.includes(:lesson).order(Arel.sql('lessons.number asc, parts.number asc'))
  }
  scope :available_for_student_to_take, lambda { |student|
    parts_taken = student.progresses.pluck(:part_id)
    next_part_to_take = ordered_parts_with_lesson.where.not(id: parts_taken)
                                                 .first&.id
    available_parts = (parts_taken << next_part_to_take).compact
    ordered_parts_with_lesson.where(id: available_parts)
  }

  def to_s
    "Lesson: #{lesson_number} Part: #{number}"
  end

  def detailed_to_s
    "#{self} | Lesson: #{lesson} | Part: #{name}"
  end
end

app/models/progress.rb
# frozen_string_literal: true

class Progress < ApplicationRecord
  belongs_to :student
  belongs_to :part
  belongs_to :course_lesson, optional: true

  delegate :previous, :lesson, :name, to: :part, prefix: true
  delegate :lesson, to: :course_lesson, prefix: true
  delegate :course, to: :course_lesson, allow_nil: true

  validates :student_id, presence: true
  validates :part_id, presence: true
  validate :lessons_can_only_be_completed_in_proper_sequence
  validate :lessons_can_only_be_taken_with_proper_course

  def course_name
    course&.name || 'Not taken with any course'
  end

  private

  def lessons_can_only_be_completed_in_proper_sequence
    return if part.blank? || part_previous.blank?
    if Progress.find_by(part: part_previous, student: student).blank?
      errors.add(:part_id, "Please complete '#{part_previous.detailed_to_s}' before trying to complete '#{part.detailed_to_s}'")
    end
  end

  def lessons_can_only_be_taken_with_proper_course
    return if part.blank? || course_lesson.blank?
    if !part_lesson.eql?(course_lesson_lesson)
      errors.add(:course_lesson_id, "'#{part.detailed_to_s}' is not offered with '#{course_lesson}'. Please select a course that offers 'Lesson: #{part_lesson.number} - #{part_lesson}'")
    end
  end
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_many :progresses

  validates :name, presence: true
end

app/models/teacher.rb
# frozen_string_literal: true

class Teacher < ApplicationRecord
  has_many :courses
  has_many :course_lessons, through: :courses
  has_many :progresses, through: :course_lessons
  has_many :students, through: :progresses

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, if: proc { |c| c.request.format.json? }

  rescue_from(ActionController::ParameterMissing) do |parameter_missing_exception|
    error = {}
    error[parameter_missing_exception.param] = ['parameter is required']
    response = { errors: [error] }
    respond_to do |format|
      format.json { render json: response, status: :unprocessable_entity }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/progresses_controller.rb
# frozen_string_literal: true

class ProgressesController < ApplicationController
  before_action :set_lookup_data

  def new
    @progress = Progress.new
  end

  def create
    if (_progress_params = params[:progress])
      _progress_params[:part_id] ||= Part.by_numbers(_progress_params[:lesson_number],
                                                     _progress_params[:part_number]).try(:id)
    end
    @progress = @student.progresses.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to student_url(@progress.student), notice: 'Progress was successfully saved.' }
        format.json do
          render partial: 'progresses/progress', locals: { progress: @progress },
                 status: :created
        end
      else
        format.html { render :new }
        format.json { render json: { errors: [{ progress: @progress.errors }] }, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_lookup_data
    @student = Student.find(params[:student_id])
    @parts = Part.available_for_student_to_take(@student)
    @course_lessons = CourseLesson.available_by_parts(@parts)
  end

  def progress_params
    params.require(:progress).permit(:part_id, :course_lesson_id, :progress_id)
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.includes(progresses: { part: [:lesson], course_lesson: [:course] })
                      .order('lessons.number desc, parts.number desc, progresses.id desc')
                      .find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json do
          render partial: 'students/student', locals: { student: @student },
                 status: :created,
                 location: @student
        end
      else
        format.html { render :new }
        format.json { render json: { errors: [{ student: @student.errors }] }, status: :unprocessable_entity }
      end
    end
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/controllers/teachers_controller.rb
# frozen_string_literal: true

class TeachersController < ApplicationController
  def index
    @teachers = Teacher.all
  end

  def show
    @teacher = Teacher.eager_load(progresses: [:student, part: [:lesson], course_lesson: [:course]],
                                  courses: [:progresses])
                      .order('progresses.student_id ASC, lessons.number desc, parts.number desc')
                      .find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= content_for :heading do %>
  Dashboard
<% end %>

<section class="jumbotron text-center">
  <h3 class="display-5">Application to manage student education</h3>
  <p>
    <%= link_to 'View Students', students_path, class: 'btn btn-primary my-2' %>
    <%= link_to 'View Teachers', teachers_path, class: 'btn btn-secondary my-2' %>
  </p>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EduX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <%= link_to 'EduX', root_path, class: 'navbar-brand col-sm-3 col-md-2 mr-0'%>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link' do %>
                  <span data-feather='home'></span>
                  Dashboard
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to students_path, class: 'nav-link' do %>
                  <span data-feather="users"></span>
                  Students
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to teachers_path, class: 'nav-link' do %>
                  <span data-feather="users"></span>
                  Teachers
                <% end %>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2"><%= yield(:heading) %></h1>
          </div>

          <% flash.each do |type, msg| %>
            <% case type %>
            <% when 'notice' %>
              <% type = 'success' %>
            <% when 'alert' %>
              <% type = 'error' %>
            <% end %>
            <% if type.present? && msg.present? && msg.is_a?(String) %>
              <div class="alert alert-<%=type%> alert-dismissible fade show" role="alert">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            <% end %>
          <% end %>

          <%= yield %>
        </main>
      </div>
    </div>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
     feather.replace()
    </script>
  </body>
</html>

app/views/progresses/_item.html.erb
<tr>
  <th scope="row"><%= progress.part %></th>
  <td><%= progress.part_lesson.name %></td>
  <td><%= progress.part_name %></td>
  <td><%= progress.course_name %></td>
  <td><%= progress.created_at.to_s(:long_ordinal)%></td>
</tr>

app/views/progresses/new.html.erb
<%= content_for :heading do %>
  Complete new lesson for <mark><%= @student.name %></mark>
<% end %>

<div class="card">
  <div class="card-body">
    <%= form_with(model: [@student, @progress], local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { f: f } %>

      <div class="form-group">
        <%= f.label :part_id, "* Select a 'Lesson and Part' for completion" %>
        <%= f.select :part_id, @parts.collect { |p| [ p.detailed_to_s, p.id ] }, { include_blank: 'Please select' }, class: 'form-control' %>
        <small class="form-text text-muted">* This is a required field.</small>
      </div>

      <div class="form-group">
        <% if @course_lessons.present? %>
          <%= f.label :course_lesson_id, "Take the above selected 'Lesson' as part of a course" %>
          <%= f.select :course_lesson_id, @course_lessons.collect { |cl| [ cl, cl.id ] }, { include_blank: 'Please select' }, class: 'form-control' %>
        <% else %>
          <span class="text-muted">Currently no courses offer above available lessons.</span>
        <% end %>
      </div>

      <div class="actions">
        <%= f.submit 'Mark as complete',  class: 'btn btn-primary btn-block', data: { disable_with: 'Saving...' }  %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if f.object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(f.object.errors.count, "error") %> prohibited record from being saved:</h2>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: [student], local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { f: f } %>

      <div class="form-group">
        <%= f.label :name, '* Student Name' %>
        <%= f.text_field :name, class: 'form-control' %>
        <small class="form-text text-muted">* This is a required field.</small>
      </div>

      <div class="actions">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/students/_progress_list.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Lesson Name</th>
      <th scope="col">Part Name</th>
      <th scope="col">Course</th>
      <th scope="col">Completion Date/Time</th>
    </tr>
  </thead>
  <tbody>
    <% student.progresses.each do |progress| %>
      <%= render partial: 'progresses/item', locals: { progress: progress } %>
    <% end %>
  </tbody>
</table>

app/views/students/index.html.erb
<% content_for :heading do %>
  Students Listing
<% end %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Student Name</th>
      <th class="text-right">
        <%= link_to 'Add new student', new_student_path, class: 'btn btn-success' %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><span class="lead"><%= link_to student.name, student_path(student) %></span></td>
        <td class="text-right"><%= link_to "View progress for #{student.name}", student_path(student), class: 'btn btn-secondary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<%= content_for :heading do %>
  New Student
<% end %>

<%= render 'form', student: @student %>

app/views/students/show.html.erb
<% content_for :heading do %>
  <%= @student.name %>
<% end %>

<%= link_to "Complete new lesson for #{@student.name}", new_student_progress_path(@student), class: 'btn btn-success' %>

<hr/>

<% if @student.progresses.present? %>
  <h4 class="section-header">Completed lessons:</h4>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Lesson Name</th>
        <th scope="col">Part Name</th>
        <th scope="col">Course</th>
        <th scope="col">Completion Date/Time</th>
      </tr>
    </thead>
    <tbody>
      <% @student.progresses.each do |progress| %>
        <tr>
          <th scope="row"><%= progress.part %></th>
          <td><%= progress.part_lesson.name %></td>
          <td><%= progress.part_name %></td>
          <td><%= progress.course_name %></td>
          <td><%= progress.created_at.to_s(:long_ordinal)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <span class="text-warning"><%= @student.name %> has not completed any lessons.</span>
<% end %>

app/views/teachers/index.html.erb
<% content_for :heading do %>
  Teachers Listing
<% end %>

<table class="table table-striped">
  <thead class="thead-light">
    <tr>
      <th>Teacher Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><span class="lead"><%= link_to teacher.name, teacher_path(teacher) %></span></td>
        <td class="text-right"><%= link_to "View report for #{teacher.name}", teacher_path(teacher), class: 'btn btn-secondary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/teachers/show.html.erb
<% content_for :heading do %>
  <%= @teacher.name %>
<% end %>

<% if @teacher.courses.present? %>
  Courses offered by <%= @teacher.name %>:
  <% @teacher.courses.each do |course| %>
    <span class="badge badge-light p-2"><%= course.name %></span>
  <% end %>
<% else %>
  <span class="text-muted"><%= @teacher.name %> does not offer any courses.</span>
<% end %>
<br />
<br />


<% if @teacher.progresses.present? %>
  <h4 class="section-header">Progress report of students taking courses offered by <%= @teacher.name%>:</h4>
  <br/>
  <% @teacher.progresses.group_by(&:student).each do |student, progresses| %>
    <div class="card mb-2">
      <div class="card-header">
        Lesson completions for <span class="mark"><%= student.name %></span>
      </div>
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Lesson Name</th>
            <th scope="col">Part Name</th>
            <th scope="col">Course</th>
            <th scope="col">Completion Date/Time</th>
          </tr>
        </thead>
        <tbody>
          <% progresses.each do |progress| %>
            <%= render partial: 'progresses/item', locals: { progress: progress } %>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
<% else %>
  <% if @teacher.courses.present? %>
    <span class="text-warning">No student has taken any of the above courses.</span>
  <% end %>
<% end %>